# Generated by Django 5.2.5 on 2025-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Title of the data breach incident')),
                ('url', models.TextField(help_text='URL to the source article or report', unique=True)),
                ('source', models.TextField(help_text='Source of the breach information (e.g., news outlet, security firm)')),
                ('summary', models.TextField(help_text='Brief summary of the data breach incident')),
                ('publish_date', models.DateTimeField(help_text='Date and time when the breach information was published')),
                ('full_text_of_article', models.TextField(help_text='Complete text content of the breach report or article')),
                ('number_of_records_breached', models.TextField(blank=True, help_text='Number of records affected by the breach (stored as string to handle various formats)', null=True)),
                ('names_of_threat_actors', models.TextField(blank=True, help_text='Names of threat actors or groups responsible for the breach', null=True)),
                ('story_cluster_id', models.CharField(blank=True, db_index=True, help_text='Unique identifier for grouping articles about the same underlying breach incident', max_length=100, null=True)),
                ('title_embedding', models.JSONField(blank=True, help_text='Vector embedding of the title text for similarity matching', null=True)),
                ('summary_embedding', models.JSONField(blank=True, help_text='Vector embedding of the summary text for similarity matching', null=True)),
                ('title_summary_embedding', models.JSONField(blank=True, help_text='Vector embedding of combined title and summary for similarity matching', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'db_table': 'news_articles',
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['publish_date'], name='news_articl_publish_0885c9_idx'), models.Index(fields=['source'], name='news_articl_source_8e92d3_idx'), models.Index(fields=['created_at'], name='news_articl_created_8afb27_idx'), models.Index(fields=['story_cluster_id'], name='news_articl_story_c_dd260b_idx')],
            },
        ),
    ]
